# Generated by Django 4.2.3 on 2023-08-07 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_header_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='header_image',
            new_name='event_image',
        ),
    ]
