# Generated by Django 4.2.3 on 2023-08-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
