# Generated by Django 4.2.3 on 2023-08-01 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contactmessage_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
